config/routes.rb
Rails.application.routes.draw do
  root to: "time_sheets#index" 
  resources :time_sheets
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/time_sheet.rb
class TimeSheet < ApplicationRecord
  belongs_to :user

  validate :clock_in_date_cannot_be_from_the_past
  validate :clock_in_date_cannot_be_after_clock_out_date

  validate :clock_out_date_cannot_be_from_the_past
  validate :clock_out_date_cannot_be_before_clock_in_date

  def clock_in_date_cannot_be_from_the_past
    if clock_in.present? && clock_in < Date.today
      errors.add(:clock_in, "can't be in the past")
    end
  end

  def clock_in_date_cannot_be_after_clock_out_date
    if (clock_out.present? && clock_in.present?) && clock_in > clock_out  
      errors.add(:clock_in, "can't be after clock out date")
    end
  end

  def clock_out_date_cannot_be_from_the_past
    if clock_out.present? && clock_out < Date.today
      errors.add(:clock_out, "can't be in the past")
    end
  end

  def clock_out_date_cannot_be_before_clock_in_date
    if (clock_out.present? && clock_in.present?) && clock_out < clock_in 
      errors.add(:clock_out, "can't be after clock out date")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :time_sheets, dependent: :nullify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates_presence_of :first_name, :last_name

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/time_sheets_controller.rb
class TimeSheetsController < ApplicationController
  before_action :set_time_sheet, only: %i[ show edit update destroy ]

  # GET /time_sheets or /time_sheets.json
  def index
    @time_sheets = current_user.time_sheets.find_each
  end

  # GET /time_sheets/1 or /time_sheets/1.json
  def show;end

  # GET /time_sheets/new
  def new
    @time_sheet = TimeSheet.new
  end

  # GET /time_sheets/1/edit
  def edit
  end

  # POST /time_sheets or /time_sheets.json
  def create
    @time_sheet = current_user.time_sheets.build(time_sheet_params)

    respond_to do |format|
      if @time_sheet.save
        format.html { redirect_to time_sheet_url(@time_sheet), notice: "Time sheet was successfully created." }
        format.json { render :show, status: :created, location: @time_sheet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @time_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_sheets/1 or /time_sheets/1.json
  def update
    respond_to do |format|
      if @time_sheet.update(time_sheet_params)
        format.html { redirect_to time_sheet_url(@time_sheet), notice: "Time sheet was successfully updated." }
        format.json { render :show, status: :ok, location: @time_sheet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @time_sheet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_sheets/1 or /time_sheets/1.json
  def destroy
    @time_sheet.destroy

    respond_to do |format|
      format.html { redirect_to time_sheets_url, notice: "Time sheet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_sheet
      @time_sheet = TimeSheet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def time_sheet_params
      params.require(:time_sheet).permit(:clock_in, :clock_out, :reason)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/time_sheets_helper.rb
module TimeSheetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HimamaAssignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/time_sheets/_clock_in_form.html.erb
<div class="field">
  <%= form.label :clock_in %>
  <%= form.datetime_select :clock_in %>
</div>

  

app/views/time_sheets/_clock_out_form.html.erb
<div class="field">
  Clocked in at <%= @time_sheet.clock_in %>
</div>

<div class="field">
  <%= form.label :clock_out %>
  <%= form.datetime_select :clock_out %>
</div>

<div class="field">
  <%= form.label :reason %>
  <%= form.text_field :reason %>
</div>

app/views/time_sheets/_edit_form.html.erb
<div class="field">
    <%= form.label :clock_in %>
    <%= form.datetime_select :clock_in %>
  </div>

  <div class="field">
    <%= form.label :clock_out %>
    <%= form.datetime_select :clock_out %>
  </div>

  <div class="field">
    <%= form.label :reason %>
    <%= form.text_field :reason %>
  </div>

app/views/time_sheets/_form.html.erb
<%= form_with(model: time_sheet, local: true) do |form| %>
  <% if time_sheet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_sheet.errors.count, "error") %> prohibited this time_sheet from being saved:</h2>

      <ul>
        <% time_sheet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if params[:type].nil? %>
    <%= render "edit_form", form: form  %>
  <% else %>
    <%= render "#{params[:type]}_form", form: form  %>
  <% end %>

  <div class="actions">
    <% action = params[:type].nil? ? "Edit" : params[:type].humanize %>
    <%= form.submit action %>
  </div>
<% end %>

app/views/time_sheets/edit.html.erb
<h1>Editing Time Sheet</h1>

<%= render "form", time_sheet: @time_sheet %>

<%= link_to 'Show', @time_sheet %> |
<%= link_to 'Back', time_sheets_path %>

app/views/time_sheets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Time Sheets for <%= current_user.full_name %></h1>

<%= link_to 'Clock In', new_time_sheet_path(type: "clock_in"), class: "clock_in_btn" %>
<%= link_to 'Clock Out', new_time_sheet_path(type: "clock_out"), class: "clock_out_btn" %>

<table>
  <thead>
    <tr>
      <th>Clock in</th>
      <th>Clock out</th>
      <th>Reason</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_sheets.each do |time_sheet| %>
      <tr>
        <td><%= time_sheet.clock_in %></td>
        <td><%= time_sheet.clock_out.blank? ? (link_to 'Clock Out', edit_time_sheet_path(time_sheet.id, type: "clock_out"), class: "clock_out_btn") : time_sheet.clock_out  %></td>
        <td><%= time_sheet.reason %></td>
        <td><%= link_to 'Show', time_sheet %></td>
        <td><%= link_to 'Edit', edit_time_sheet_path(time_sheet, type: "edit") %></td>
        <td><%= link_to 'Destroy', time_sheet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/time_sheets/new.html.erb
<h1>New Time Sheet</h1>

<%= render "form", time_sheet: @time_sheet %>

<%= link_to 'Back', time_sheets_path %>

app/views/time_sheets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Clock in:</strong>
  <%= @time_sheet.clock_in %>
</p>

<p>
  <strong>Clock out:</strong>
  <%= @time_sheet.clock_out %>
</p>

<p>
  <strong>Reason:</strong>
  <%= @time_sheet.reason %>
</p>

<%= link_to 'Edit', edit_time_sheet_path(@time_sheet) %> |
<%= link_to 'Back', time_sheets_path %>